// USER
export const USER_LOGIN = 'USER_LOGIN';
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_LOGOUT = 'USER_LOGOUT';
export const GET_DATA = 'GET_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const GET_LANGUAGES = 'GET_LANGUAGES';
export const ERROR_MODAL = 'ERROR_MODAL';
export const COUNTER_CHANGE = 'COUNTER_CHANGE';
export const GET_REVIEWS_RATINGS_COUNT = 'GET_REVIEWS_RATINGS_COUNT';
export const GET_ALL_REVIEWS = 'GET_ALL_REVIEWS';
export const GET_CURRENT_BOOKING = 'GET_CURRENT_BOOKING';
export const BOOKING_HISTORY = 'BOOKING_HISTORY';
export const UPDATE_PHOTO = 'UPDATE_PHOTO';
export const GET_CURRENT_LOC = 'GET_CURRENT_LOC';
export const FIREBASE_DATA = 'FIREBASE_DATA'
